version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/aws:2023.04.1
    steps:
      - checkout
      - run:
          name: Completely empty bucket 
          command: |
            # 1. Delete everything inside the bucket
            aws s3 rm s3://$AWS_S3_BUCKET/ --recursive
            
